version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8899:8000"
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
    ports:
      - "3360:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: